### ISSUE TITLE
HTML tag prints invalid language attribute

### ISSUE THREAD

**Issue by kishanjasani** [imranhsayed/aquila#20]
In header.php you have used `<html lang="<?php language_attributes(); ?>">` which prints like
` <html lang="lang=" en-us""=""> ` that is an unexpected behavior. 

Just use `<html <?php language_attributes(); ?>>`

By the way thanks for all beautiful tutorials :+1:

**Comment by imranhsayed** [comment]
👍 Done Thanks for highlighting @kishanjasani
