### ISSUE TITLE
Metabox functionality hide and display title is not working

### ISSUE THREAD

**Issue by kishanjasani** [imranhsayed/aquila#21]
Current behavior: The title is not hidden on a single page even if we select to hide it from the meta box.

In the `template-parts/components/blog/entry-header.php` change class name from `hide` to bootstrap class`d-none`

`$heading_class = ! empty( $hide_title ) && 'yes' === $hide_title ? 'd-none' : '';`

**Comment by imranhsayed** [comment]
👍 Done. Thanks @kishanjasani
