### ISSUE TITLE
Implement Slick Slider

### ISSUE THREAD

**Issue by onnoverbeek** [imranhsayed/aquila#23]
Hi Imran, 

Thanx for your great tutorials, they're really helpful and I learned a lot of new things. Especially those patterns are awesome. Is it possible to make a pattern for a slick slider, with controls in the customizer? 

So we can add pictures true customizer, and change the settings. It would be really great if we can adjust the sizes for the images as well.

Cheers.

**Comment by imranhsayed** [comment]
Thank you!
I created a [WordPress plugin](https://wordpress.org/plugins/sage-slider/) for the same from https://www.youtube.com/watch?v=qpAzpfFR40k

You can check the code.
I shall consider creating customizer videos in future, which will help you understand the implementation better

**Comment by onnoverbeek** [comment]
It works fine with the Slack post resolution
