### ISSUE TITLE
Add WooCommerce support

### ISSUE THREAD

**Issue by onnoverbeek** [imranhsayed/aquila#44]
Hi Imran, 

I'm trying to add woocommerce support for custom woocommerce pages. 
As long as I add the woocommerce.php it works fine, but the folder of /woocommerce won't work. 

With that issue, i'm only able to add the default woocommerce styles in woocommerce.php instead of the custom woocommerce/archive-product.php and others.

**Comment by imranhsayed** [comment]
The question better belongs to WooCommerce theme
https://github.com/imranhsayed/advanced-woocommerce-theme
