### ISSUE TITLE
Blog post infinite scroll

### ISSUE THREAD

**Issue by ivanmitic91** [imranhsayed/aquila#65]
Please make a video on how to add infinite scroll for posts, as you said at beginning of course, that is a key feature, and if you can also option for 'load more'

**Comment by imranhsayed** [comment]
Yep, I shall add that in future videos.

**Comment by ivanmitic91** [comment]
Thank you, you are amazing!

**Comment by imranhsayed** [comment]
This one is complete @ivanmitic91

**Comment by ivanmitic91** [comment]
Wow , thank you ! I wish you all the best
